### ISSUE TITLE
i cant use the vscode plugin sudden

### ISSUE THREAD

**Issue by noahxinhao** [ferib/lua-obfuscator-plugin#9]
I checked the api interface and found that Cloudflare blocked the request.and i got an error "failed upload script". is there some update make it unavailable？ 
the pic show in vscode
<img width="460" alt="截屏2024-01-31 17 08 05" src="https://github.com/ferib/lua-obfuscator-plugin/assets/6268952/6cc8fcaa-5e1b-4b2d-8b31-86e5b833bd3b">

this pic show when i request the api direct.
<img width="894" alt="截屏2024-01-31 17 08 31" src="https://github.com/ferib/lua-obfuscator-plugin/assets/6268952/c0be12a5-b354-45dc-9222-12f2c30b3c66">

**Comment by ferib** [comment]
Hi, the default API key `test` has been disabled due to ongoing DDoS attacks. Please, for the time being, reach out to me to obtain a new key 😊 

I think soon:tm: you will be able to generate a API Key from https://luaobfuscator.com/forum/keys/

<img width="313" alt="image" src="https://github.com/ferib/lua-obfuscator-plugin/assets/22753171/f4bd1a9c-ad91-45b0-a58a-30f863f4d932">

**Comment by noahxinhao** [comment]
When can it be restored?

**Comment by ferib** [comment]
Please enter the Discord channel, https://discord.gg/vYrmxByrWq, and reach out to me

**Comment by ferib** [comment]
Fix to change default hardcoded key has been added in #10
